services:
  - type: web
    name: 9xdhamaka-app
    env: python
    pythonVersion: "3.10.6"
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet --workers 1 --threads 100 --bind 0.0.0.0:$PORT --timeout 120 'app:app'"
    envVarGroups:
      - name: 9xdhamaka-secrets